#!/bin/bash
# shellcheck disable=SC2059

clear="\e[H\e[2J"
black="\e[30m"
red="\e[31m"
yellow="\e[33m"
magenta="\e[35m"
white="\e[37m"
reset="\e[0m"

printf "${clear}${yellow}Answer me these questions three, 'ere the other side ye see:${reset}\n"

printf "${magenta}What is your name? ${white}"
read -r name
printf "${reset}"

printf "${black}You entered: ${red}$name${reset}\n"

printf "${yellow}What is your quest?${reset}\n"

if [[ ${name,,} =~ rob ]]; then
	echo yes
fi

# lname=$(printf "$name" | tr '[:upper:]' '[:lower:]')
# 
# case $name in
# 
# 	rob*)
# 		printf "${yellow}What is your capital of Assyria? ${white}\n";;
# 
# 	lancelot)
# 
# 		printf "${yellow}What is your favorite colour? ${white}\n";;
# 
# 	arthur)
# 		printf "${yellow}What is the air speed velocity of an unladen swallow? ${white}\n";
# 		printf "How do you know so much about swallows?\n";
# 		printf "Well, as a King you have to know these things you know.\n";;
# 
# 	*)
# 		printf "What is your favorite colour?\n";;
# 
# esac

printf "${yellow}Would you like to play again? [n] ${reset}: ${white}\n"
read -r yes
printf "${reset}"

case $yes in
	[Yy]) printf "Okay";;
	*) printf "Fine";;
esac
